### ISSUE TITLE
First frame render

### ISSUE THREAD

**Issue by gaou-piou** [tweenrex/tweenrex#10]
Using 
`onFinish: () => tween.restart()`
first frame is not correct

look at this example
https://codepen.io/gaougalos/pen/ooJyrM

**Comment by notoriousb1t** [comment]
I think I know what is happening here, but first, some notes on the internals:

- all subtweens get the progress value (0-1) each tick
- tweens only publish to subscribers new values by default. So subsequent values are ignored 
- tweens are notified in the order they are configured (regardless of position and direction)

As a result, when you seek forward and target the same object and property, everything works as expected.  When you seek backward, because multiple interpolate functions target the same object and property, the last one to be configured is the last one to modify the property.

I have a good idea of how to fix this.  In a nutshell, it needs to order the tweens by position ascending and when the new seek position is behind the current position, it needs to call the tweens by endPosition descending.

I will try to address this later today.  With any luck, a fix will be out tonight.

As an aside, that animation looks pretty clean outside of this issue.

**Comment by notoriousb1t** [comment]
@gaou-piou Please update to 1.3.1 and let me know if that works for you 😄

**Comment by gaou-piou** [comment]
Yeah. It works
