### ISSUE TITLE
Feature aliases

### ISSUE THREAD

**Issue by notoriousb1t** [tweenrex/tweenrex#5]
I was looking through the code of recurve and I noticed there are a few cases where a top level function is really an alias of another.  For instance:

**weighted vs combine**
https://github.com/tweenrex/recurve/blob/master/src/compositors/index.ts

**pad vs clamp**
https://github.com/tweenrex/recurve/blob/master/src/normalizers/index.ts

I think we should pick one name, whichever is most generally applicable.  Doing so will reduce the need to document and will make usage clearer.

**Comment by jhnsnc** [comment]
There are a few places where users will be split on their expectation of the names. For example `Power5` vs `Quint` easing.

There are other cases where I think the most appropriate name depends on how it's being used in the moment. The same function/code can be used to `pad` a timeline or `clamp` an easing value. If we choose one name for it, the term will feel less natural/expressive for one use or the other.

I definitely agree that we want to be opinionated and not alias names due to indecisiveness, but I think there are also some valid reasons for aliasing.

Oh, the thought process behind aliasing `weighted`/`combine` is: When I want to combine multiple easing functions into one function based on relative "weight", the `weighted` function makes sense. If I want to provide functions with specific offsets, the `piecewise` function makes sense. But if I just want to combine easing functions in the simplest way possible, it's hard for me to know whether `weighted` or `piecewise` is going to be easier to use--neither name gives me a hint. So we alias `weighted` as `combine` since it can be used the most directly (e.g. `var easing = tr.r.combine([ease1,ease2])`).

**Comment by notoriousb1t** [comment]
>There are a few places where users will be split on their expectation of the names. For example Power5 vs Quint easing.

I think as far as power5 vs quint goes, it would be better to pick one.  I am on the side of power5 because it is easier for someone who speaks english as a second language to know that power4 is less than power5 whereas quad vs quint might not be as immediately clear.  Not picking one here might make the docs confusing, and while users might be split I think it will be a tiny bump in the road in the scheme of things

>There are other cases where I think the most appropriate name depends on how it's being used in the moment. The same function/code can be used to pad a timeline or clamp an easing value. If we choose one name for it, the term will feel less natural/expressive for one use or the other.

I see your argument about aliasing for clamp and pad because it might read strange.  Maybe minMax like from grid layout might describe both since it doesn't imply intent, just values?  I suppose clamp/pad are pretty standard though, so I have no issue with keeping both.

>Oh, the thought process behind aliasing weighted/combine is: When I want to combine multiple easing functions into one function based on relative "weight", the weighted function makes sense

I think "mixEasing" instead of combine/weighted might be descriptive enough if we changed the usage a little.  If I understand the intent correctly:

"Combine"
```js
const combined = tweenrex.mixEasing([tweenrex.back.in, tweenrex.back.out])
```

Then if we allowed specifying options in place of the function rather than a separate array and distributed the remainder:

"Weighted"
```js
const combined = tweenrex.mixEasing([
    tweenrex.back.in, 
    tweenrex.elastic.in,
    { easing: tweenrex.back.out, weight: 0.4 }
])
```

In that case back.in and elastic.in would each get 30% of the weight and back.out would get 40%.

One thing we have to be careful about here is that all top-level functions/objects are unique vs other modules (but that is a different discussion)
