### ISSUE TITLE
Normalizer: reverse()

### ISSUE THREAD

**Issue by notoriousb1t** [tweenrex/tweenrex#6]
I love the idea of using easings to handle repeat, alternating, etc.  I think we should add an easing that flips the easing.

So..
0.2 -> 0.8, 
-0.02 -> 1.02

Something like...

```js
const tween = TweenRex({
    duration: 1000,
    subscribe: interpolate({
        targets: '#target',
        easing: reverse,
        opacity: 0
    })
})
```

Since interpolate uses the original value (of 1) on the object, this would flip the animation from opacity:
 [1, 0] to opacity: [0, 1] effectively providing an easy way to tween to the current value (whatever that is) from a specific value.

**Comment by jhnsnc** [comment]
I had originally excluded this function, but we can include it. I'm not sure what category I would put it in.

But the function implementation is basically just:
```
function reverse(n) {
    return 1 - n;
}
```

So I hadn't originally included it because it actually is easier to type `(n=>1-n)(n)` than `tr.r.reverse(n)`. But I definitely see the value in terms of making the API more expressive.

Perhaps it would go in the `normalizers` group? Maybe we need a better term for this category of util?

**Comment by notoriousb1t** [comment]
As for the current structure goes, I think reverse makes the most sense as a normalizer.  

I see the value because of API expressiveness as you mentioned.  Plus, I think most the nuance of how the easings actually work is lost on the majority of people who use them.  

We probably should figure https://github.com/tweenrex/tweenrex/issues/7 out before adding this.
